package br.ufal.ic.parser;

import javafx.util.Pair;

import java.util.Arrays;
import java.util.Hashtable;
import java.util.List;

public class ParsingTable {

    private static Hashtable<Pair<String, String>, List<String>> parsingTable;

    public static void fillParsingTable() {
        addToParsingTable("S", "defmod", Arrays.asList("defmod", "id", "do", "Global", "DeclFuncoes", "endmod"));
        addToParsingTable("Global", "endmod", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "def", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "int", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "void", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "str", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "real", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "bool", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "char", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "$", Arrays.asList("RDeclVar"));
        addToParsingTable("Global", "EOF", Arrays.asList("RDeclVar"));
        addToParsingTable("DeclFuncoes", "endmod", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("DeclFuncoes", "def", Arrays.asList("Funcao", "DeclFuncoes"));
        addToParsingTable("Funcao", "def", Arrays.asList("def", "TipoFuncao", "id", "(", "Parametro", ")", "do", "Instrucao", "end"));
        addToParsingTable("Return", "return", Arrays.asList("return", "Exp", ";"));
        addToParsingTable("TipoFuncao", "int", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFuncao", "void", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFuncao", "str", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFuncao", "real", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFuncao", "bool", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFuncao", "char", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("FArr", "id", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "endmod", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "def", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "[", Arrays.asList("[", "RFArr", "]"));
        addToParsingTable("FArr", "int", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "void", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "str", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "real", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "bool", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "char", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "$", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("FArr", "EOF", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RFArr", "id", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "(", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RFArr", "~", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "-", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "cteI", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "cteR", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "cteStr", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "cteChar", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "true", Arrays.asList("Exp"));
        addToParsingTable("RFArr", "false", Arrays.asList("Exp"));
        addToParsingTable("Tipo", "int", Arrays.asList("int"));
        addToParsingTable("Tipo", "void", Arrays.asList("void"));
        addToParsingTable("Tipo", "str", Arrays.asList("str"));
        addToParsingTable("Tipo", "real", Arrays.asList("real"));
        addToParsingTable("Tipo", "bool", Arrays.asList("bool"));
        addToParsingTable("Tipo", "char", Arrays.asList("char"));
        addToParsingTable("TipoFixo", "int", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFixo", "void", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFixo", "str", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFixo", "real", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFixo", "bool", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("TipoFixo", "char", Arrays.asList("Tipo", "FArr"));
        addToParsingTable("Parametro", "id", Arrays.asList("id", ":", "TipoFixo", "Parametro"));
        addToParsingTable("Parametro", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Parametro", ",", Arrays.asList(",", "id", ":", "TipoFixo"));
        addToParsingTable("Instrucao", "id", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "do", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "end", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "return", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "int", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "void", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "str", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "real", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "bool", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "char", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "when", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "otherwise", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "until", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "till", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("Instrucao", "rep", Arrays.asList("Comando", "RInstrucao"));
        addToParsingTable("RInstrucao", "end", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RInstrucao", "otherwise", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RInstrucao", "till", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Comando", "id", Arrays.asList("id", "RArr", "ComandoX", "Comando"));
        addToParsingTable("Comando", "do", Arrays.asList("DoUntil", "Comando"));
        addToParsingTable("Comando", "end", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Comando", "return", Arrays.asList("Return"));
        addToParsingTable("Comando", "int", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "void", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "str", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "real", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "bool", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "char", Arrays.asList("TipoFixo", "id", "ComandoA", ";", "Comando"));
        addToParsingTable("Comando", "when", Arrays.asList("When", "Comando"));
        addToParsingTable("Comando", "otherwise", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Comando", "until", Arrays.asList("Until", "Comando"));
        addToParsingTable("Comando", "till", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Comando", "rep", Arrays.asList("Rep", "Comando"));
        addToParsingTable("ComandoX", "(", Arrays.asList("(", "ParFunc", ")", ";"));
        addToParsingTable("ComandoX", "=", Arrays.asList("=", "Exp", ";"));
        addToParsingTable("ComandoA", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("ComandoA", "=", Arrays.asList("=", "Exp"));
        addToParsingTable("Atrib", "id", Arrays.asList("Id", "=", "Exp", ";"));
        addToParsingTable("Atrib", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Id", "id", Arrays.asList("id", "Arr"));
        addToParsingTable("RDeclVar", "endmod", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RDeclVar", "def", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RDeclVar", "int", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "void", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "str", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "real", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "bool", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "char", Arrays.asList("DeclVar", "RDeclVar"));
        addToParsingTable("RDeclVar", "$", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RDeclVar", "EOF", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("DeclVar", "int", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("DeclVar", "void", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("DeclVar", "str", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("DeclVar", "real", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("DeclVar", "bool", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("DeclVar", "char", Arrays.asList("TipoFixo", "Atrib", ";"));
        addToParsingTable("Arr", "[", Arrays.asList("[", "Exp", "]"));
        addToParsingTable("Arr", "=", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "(", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "[", Arrays.asList("[", "LRArr", "]"));
        addToParsingTable("RArr", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "=", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "opr2", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "opr1", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "$", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "opa", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "opm", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RArr", "EOF", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("LRArr", "id", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "(", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("LRArr", "~", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "-", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "cteI", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "cteR", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "cteStr", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "cteChar", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "true", Arrays.asList("Exp"));
        addToParsingTable("LRArr", "false", Arrays.asList("Exp"));
        addToParsingTable("When", "when", Arrays.asList("when", "(", "Exp", ")", "do", "Otherwise", "end"));
        addToParsingTable("Otherwise", "id", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "do", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "end", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "return", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "int", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "void", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "str", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "real", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "bool", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "char", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "when", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "otherwise", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "until", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("Otherwise", "rep", Arrays.asList("Instrucao", "OtherwiseR"));
        addToParsingTable("OtherwiseR", "end", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("OtherwiseR", "otherwise", Arrays.asList("otherwise", "Instrucao"));
        addToParsingTable("Until", "until", Arrays.asList("until", "(", "Exp", ")", "do", "Instrucao", "end"));
        addToParsingTable("DoUntil", "do", Arrays.asList("do", "Instrucao", "till", "(", "Exp", ")", "end"));
        addToParsingTable("Rep", "rep", Arrays.asList("rep", "(", "VarControl", ",", "Exp", ",", "Id", "=", "Exp", ")", "do", "Instrucao", "end"));
        addToParsingTable("VarControl", "id", Arrays.asList("id", ":", "Tipo", "=", "Exp"));
        addToParsingTable("ParFunc", "id", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "(", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("ParFunc", "~", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "-", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "cteI", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "cteR", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "cteStr", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "cteChar", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "true", Arrays.asList("RParFunc"));
        addToParsingTable("ParFunc", "false", Arrays.asList("RParFunc"));
        addToParsingTable("RParFunc", "id", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "(", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "~", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "-", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "cteI", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "cteR", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "cteStr", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "cteChar", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "true", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("RParFunc", "false", Arrays.asList("Exp", "TRParFunc"));
        addToParsingTable("TRParFunc", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("TRParFunc", ",", Arrays.asList(",", "Exp", "TParFunc"));
        addToParsingTable("TParFunc", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Exp", "id", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "(", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "~", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "-", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "cteI", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "cteR", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "cteStr", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "cteChar", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "true", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("Exp", "false", Arrays.asList("ExpBoolAnd", "RExp"));
        addToParsingTable("RExp", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExp", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExp", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExp", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExp", "||", Arrays.asList("||", "ExpBoolAnd", "RExp"));
        addToParsingTable("ExpBoolAnd", "id", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "(", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "~", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "-", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "cteI", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "cteR", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "cteStr", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "cteChar", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "true", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpBoolAnd", "false", Arrays.asList("ExpRDois", "RExpBoolAnd"));
        addToParsingTable("RExpBoolAnd", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpBoolAnd", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpBoolAnd", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpBoolAnd", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpBoolAnd", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpBoolAnd", "&&", Arrays.asList("&&", "ExpRDois", "RExpBoolAnd"));
        addToParsingTable("ExpRDois", "id", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "(", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "~", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "-", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "cteI", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "cteR", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "cteStr", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "cteChar", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "true", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("ExpRDois", "false", Arrays.asList("ExpRUm", "RExpRDois"));
        addToParsingTable("RExpRDois", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRDois", "opr2", Arrays.asList("opr2", "ExpRUm"));
        addToParsingTable("ExpRUm", "id", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "(", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "~", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "-", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "cteI", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "cteR", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "cteStr", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "cteChar", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "true", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("ExpRUm", "false", Arrays.asList("ExpConcat", "RExpRUm"));
        addToParsingTable("RExpRUm", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", "opr2", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpRUm", "opr1", Arrays.asList("opr1", "ExpConcat", "RExpRUm"));
        addToParsingTable("ExpConcat", "id", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "(", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "~", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "-", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "cteI", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "cteR", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "cteStr", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "cteChar", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "true", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("ExpConcat", "false", Arrays.asList("Expa", "RExpConcat"));
        addToParsingTable("RExpConcat", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "opr2", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "opr1", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpConcat", "$", Arrays.asList("$", "Expa", "RExpConcat"));
        addToParsingTable("RExpConcat", "EOF", Arrays.asList("$", "Expa", "RExpConcat"));
        addToParsingTable("Expa", "id", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "(", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "~", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "-", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "cteI", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "cteR", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "cteStr", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "cteChar", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "true", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("Expa", "false", Arrays.asList("Expm", "RExpa"));
        addToParsingTable("RExpa", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "opr2", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "opr1", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "$", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpa", "opa", Arrays.asList("opa", "Expm", "RExpa"));
        addToParsingTable("RExpa", "EOF", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("Expm", "id", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "(", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "~", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "-", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "cteI", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "cteR", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "cteStr", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "cteChar", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "true", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("Expm", "false", Arrays.asList("ExpU", "RExpm"));
        addToParsingTable("RExpm", ")", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", ";", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "]", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", ",", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "||", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "&&", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "opr2", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "opr1", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "$", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "opa", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("RExpm", "opm", Arrays.asList("opm", "ExpU", "RExpm"));
        addToParsingTable("RExpm", "EOF", Arrays.asList(GrammarResources.getEpsilon()));
        addToParsingTable("ExpU", "id", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "(", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "~", Arrays.asList("Unario", "Fa"));
        addToParsingTable("ExpU", "-", Arrays.asList("Unario", "Fa"));
        addToParsingTable("ExpU", "cteI", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "cteR", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "cteStr", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "cteChar", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "true", Arrays.asList("Fa"));
        addToParsingTable("ExpU", "false", Arrays.asList("Fa"));
        addToParsingTable("Unario", "~", Arrays.asList("~"));
        addToParsingTable("Unario", "-", Arrays.asList("-"));
        addToParsingTable("Fa", "id", Arrays.asList("id", "RFa"));
        addToParsingTable("Fa", "(", Arrays.asList("(", "Exp", ")"));
        addToParsingTable("Fa", "cteI", Arrays.asList("Cte"));
        addToParsingTable("Fa", "cteR", Arrays.asList("Cte"));
        addToParsingTable("Fa", "cteStr", Arrays.asList("Cte"));
        addToParsingTable("Fa", "cteChar", Arrays.asList("Cte"));
        addToParsingTable("Fa", "true", Arrays.asList("Cte"));
        addToParsingTable("Fa", "false", Arrays.asList("Cte"));
        addToParsingTable("RFa", "(", Arrays.asList("(", "ParFunc", ")"));
        addToParsingTable("RFa", ")", Arrays.asList("RArr"));
        addToParsingTable("RFa", ";", Arrays.asList("RArr"));
        addToParsingTable("RFa", "[", Arrays.asList("RArr"));
        addToParsingTable("RFa", "]", Arrays.asList("RArr"));
        addToParsingTable("RFa", ",", Arrays.asList("RArr"));
        addToParsingTable("RFa", "||", Arrays.asList("RArr"));
        addToParsingTable("RFa", "&&", Arrays.asList("RArr"));
        addToParsingTable("RFa", "opr2", Arrays.asList("RArr"));
        addToParsingTable("RFa", "opr1", Arrays.asList("RArr"));
        addToParsingTable("RFa", "$", Arrays.asList("RArr"));
        addToParsingTable("RFa", "opa", Arrays.asList("RArr"));
        addToParsingTable("RFa", "opm", Arrays.asList("RArr"));
        addToParsingTable("RFa", "EOF", Arrays.asList("RArr"));
        addToParsingTable("Cte", "cteI", Arrays.asList("cteI"));
        addToParsingTable("Cte", "cteR", Arrays.asList("cteR"));
        addToParsingTable("Cte", "cteStr", Arrays.asList("cteStr"));
        addToParsingTable("Cte", "cteChar", Arrays.asList("cteChar"));
        addToParsingTable("Cte", "true", Arrays.asList("CteBool"));
        addToParsingTable("Cte", "false", Arrays.asList("CteBool"));
        addToParsingTable("CteBool", "true", Arrays.asList("true"));
        addToParsingTable("CteBool", "false", Arrays.asList("false"));
    }

    @SuppressWarnings("unchecked")
    private static void addToParsingTable(String nonTerminal, String terminal, List<String> production) {
        Pair pair = new Pair(nonTerminal, terminal);
        parsingTable.put(pair, production);
    }

    public static Hashtable<Pair<String, String>, List<String>> getParsingTable(){

        if(parsingTable == null){
            parsingTable = new Hashtable<>();
            fillParsingTable();
        }

        return parsingTable;
    }

}
